In [ ]:
#Intro
* SHape
* Joining array

In [4]:
import numpy as np

# Reshaping Arrays
### Changing Shape with .shape Attribute

In [6]:
n1 = np.array([[1,2,3,4],[1,2,3,4]])
n1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
n1.shape

(2, 4)

In [11]:
n1.shape = (4,2)
n1

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### Explanation:

* n1.shape = (4, 2) reshapes the array n1 into 4 rows and 2 columns
* This is an in-place operation - it modifies the original array n9 directly
* The tuple (4, 2) specifies the new shape:

4 = number of rows  
2 = number of columns  


Total elements must match: Original array must have exactly 8 elements (4 × 2 = 8)

### Visual Transformation:
Before: [0, 1, 2, 3, 4, 5, 6, 7]  (1D array with 8 elements)  

After:  [[0, 1],                   (2D array: 4 rows × 2 columns)
         [2, 3],
         [4, 5],
         [6, 7]]
### How Elements are Arranged:

* Elements fill the array row by row (row-major order)
* First row gets elements 0, 1
* Second row gets elements 2, 3
* Third row gets elements 4, 5
* Fourth row gets elements 6, 7

### Key Points:

* Modifies original array - does not create a new array
* Number of elements cannot change (8 elements → 8 elements)
* Valid shapes for 8 elements: (8,), (1, 8), (8, 1), (2, 4), (4, 2)
* Invalid shapes like (3, 3) will raise an error (3×3=9 ≠ 8)

### Common Reshaping Examples:

In [13]:
# 1D to 2D
arr = np.arange(12)        # [0 1 2 3 4 5 6 7 8 9 10 11]
arr.shape = (3, 4)         # 3 rows, 4 columns
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# 1D to 3D
arr = np.arange(24)
arr.shape = (2, 3, 4)      # 2 blocks, 3 rows, 4 columns


In [15]:
# 2D to 1D (flatten)
arr = np.array([[1, 2], [3, 4]])
arr.shape = (4,)           # [1 2 3 4]

In [16]:
# Making a column vector
arr = np.arange(5)
arr.shape = (5, 1)         # 5 rows, 1 column

### When to use .shape = :

* Reorganizing data into different dimensions
* Preparing data for specific operations or functions
* Matrix operations that require specific shapes
* Image processing - converting 1D pixel data to 2D/3D

### Alternative: reshape() method

In [17]:
# Creates a NEW array (doesn't modify original)
n1_reshaped = n1.reshape(4, 2)  # Original n9 unchanged

### Difference between .shape = and .reshape():

* .shape = (4, 2) → Modifies original array in-place
* .reshape(4, 2) → Returns new array, original unchanged

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # 2 rows, 3 columns
print(reshaped)


[[1 2 3]
 [4 5 6]]


# Concatenation
### Vertical Stacking with vstack()

In [19]:
n2 = np.array([10,20,30])
n3 = np.array([40,50,60])

In [21]:
# Stack them vertically (one on top of the other)
np.vstack((n2,n3))

array([[10, 20, 30],
       [40, 50, 60]])

### Explanation:

* np.vstack((n2, n3)) vertically stacks two arrays
* "vstack" = Vertical Stack = stacking arrays on top of each other
* Takes a tuple of arrays as input: (n2, n3) - note the double parentheses
* n2 becomes the first row: [10, 20, 30]
* n3 becomes the second row: [40, 50, 60]
* Creates a 2D array with 2 rows and 3 columns

### Visual Representation:

### Key Points:

* Arrays must have the same number of elements (or compatible shapes)
* Both n2 and n3 have 3 elements, so they stack correctly
* Returns a new array (doesn't modify original arrays)
* Result is always a 2D array (even if inputs are 1D)

### Requirements:

* All arrays must have the same width (number of columns)
* n2 has 3 elements → will become 3 columns
* n3 has 3 elements → will become 3 columns

### Stacking Multiple Arrays:

In [24]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.array([7, 8, 9])

result = np.vstack((a1, a2, a3))
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Stacking 2D Arrays:

In [25]:
arr1 = np.array([[1, 2], [3, 4]])  # 2×2 array
arr2 = np.array([[5, 6], [7, 8]])  # 2×2 array

result = np.vstack((arr1, arr2))
result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### When to use vstack():

* Combining datasets with same features (columns)
* Adding new samples/rows to existing data
* Building matrices row by row
* Appending observations in data analysis
* Time series data - adding new time periods

## Horizontal Stacking with hstack()

In [27]:
np.hstack((n2,n3))

array([10, 20, 30, 40, 50, 60])

### Explanation:

* np.hstack((n2, n3)) horizontally stacks two arrays
* "hstack" = Horizontal Stack = placing arrays side by side
* Takes a tuple of arrays as input: (n2, n3) - note the double parentheses
* n2 elements come first: [10, 20, 30]
*n3 elements come next: [40, 50, 60]
* Creates a 1D array with all elements combined: [10, 20, 30, 40, 50, 60]

### Visual Representation:

In [ ]:
n2: [10, 20, 30]    n3: [40, 50, 60]
         ↓ hstack (side by side)
Result: [10, 20, 30, 40, 50, 60]    (1D array with 6 elements)

### Key Points:

* Arrays must have compatible shapes for horizontal stacking
* For 1D arrays: they simply concatenate end-to-end
* Returns a new array (doesn't modify original arrays)
* Result stays 1D when stacking 1D arrays

### Horizontal Stacking with 2D Arrays:

In [28]:
arr1 = np.array([[1, 2], [3, 4]])  # 2×2 array
arr2 = np.array([[5, 6], [7, 8]])  # 2×2 array

result = np.hstack((arr1, arr2))
result

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Explanation:  
For 2D arrays, hstack() adds columns (stacks horizontally). Each row gets extended with corresponding values from the other array.
### When to use hstack():

* Combining features/columns for the same samples
* Extending arrays with new data points
* Concatenating sequences end-to-end
* Adding new features to a dataset
* Merging measurements from different sources

### Example Use Cases:

In [ ]:
# Combining product IDs with prices
product_ids = np.array([101, 102, 103])
prices = np.array([25, 30, 22])
combined = np.hstack((product_ids, prices))
# Output: [101, 102, 103, 25, 30, 22]

# Adding a new feature to dataset
heights = np.array([[170], [165], [180]])  # 3 people, 1 feature
weights = np.array([[70], [65], [85]])     # 3 people, 1 feature
data = np.hstack((heights, weights))
# Output:
# array([[170, 70],
#        [165, 65],
#        [180, 85]])  # 3 people, 2 features

### Column Stacking with column_stack()

In [29]:
# Using the same arrays from before
n2 = np.array([10, 20, 30])
n3 = np.array([40, 50, 60])

# Stack them as columns
np.column_stack((n2, n3))

array([[10, 40],
       [20, 50],
       [30, 60]])

### Explanation:

* np.column_stack((n2, n3)) stacks 1D arrays as columns in a 2D array
* Takes a tuple of arrays as input: (n2, n3) - note the double parentheses
* n2 becomes the first column: [10, 20, 30]
* n3 becomes the second column: [40, 50, 60]
* Creates a 2D array with 3 rows and 2 columns
* Each array element becomes a row in the result

### Visual Representation:

### Key Points:

* Specifically designed for turning 1D arrays into columns
* Arrays must have the same length (same number of elements)
* Returns a 2D array where each input array becomes a column
* Very useful for creating datasets with multiple features

#### Stacking Multiple Arrays as Columns:

In [31]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.array([7, 8, 9])

result = np.column_stack((a1, a2, a3))
result

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Explanation: 
* Each array becomes a column. Result has as many columns as input arrays.
### When to use column_stack():

* Creating datasets where each array represents a different feature/variable
* Combining measurements of different types for the same samples
* Building data matrices for machine learning
* Organizing related data into tabular format
* Pairing coordinates (x, y coordinates, time-value pairs)

### Example Use Cases:

In [ ]:
# Creating a dataset with multiple features
names_ids = np.array([101, 102, 103])      # Student IDs
math_scores = np.array([85, 92, 78])       # Math scores
english_scores = np.array([90, 88, 95])    # English scores

dataset = np.column_stack((names_ids, math_scores, english_scores))
# Output:
# array([[101,  85,  90],
#        [102,  92,  88],
#        [103,  78,  95]])
# 3 students × 3 features (ID, Math, English)

# Creating (x, y) coordinate pairs
x_coords = np.array([1, 2, 3, 4])
y_coords = np.array([2, 4, 6, 8])
points = np.column_stack((x_coords, y_coords))
# Output:
# array([[1, 2],
#        [2, 4],
#        [3, 6],
#        [4, 8]])
# 4 points with (x, y) coordinates